In [1]:
import pandas as pd
import numpy as np
from itertools import compress

In [2]:
def tsv_to_dataframe(file_tsv):
    '''
    this function transforms Eurostat tsv file in pandas dataframe
    file_tsv: file name. It's work with tsv and compressed file "tsv.gz"
    '''
    
    def clean_cells(x):
        '''This function transforms Eurostat Missing Values ": " in numpy missing values.
        Then clean Eurostat annotation "b, u, .."'''
        try:
            return float(x)
        except:
            try:
                return float(x.split(" ")[0])
            except:
                return np.nan
    # open the Eurostat TSV file 

    data = pd.read_csv(file_tsv, sep="\t")
    # Create a dataframe for values data
    data_clean = data
    # Clean data values with clean_cells function
    data_clean = data_clean.applymap(lambda x: clean_cells(x))
    # Drop column with variable name like "age,isced11,unit,sex,geo\time". It is the first column. we have a 
    # dataframe with only data values 
    data_clean.drop(data_clean.columns[0], axis = 1, inplace = True)
    # transform column with variable in multiple-columns  
    variabili = data[data.columns[0]].apply(lambda x: pd.Series(x.split(",")))
    variabili.columns = data.columns[0].split(",")
    # return cleaned dataframe in pandas dataframe
    return pd.concat([variabili, data_clean], axis = 1)

In [3]:
def tsv_to_dataframe_long(file_tsv):
    '''
    this function transforms Eurostat tsv file in pandas dataframe
    file_tsv: file name. It's work with tsv and compressed file "tsv.gz"
    '''
    
    def clean_cells(x):
        '''This function transforms Eurostat Missing Values ": " in numpy missing values.
        Then clean Eurostat annotation "b, u, .."'''
        try:
            return float(x)
        except:
            try:
                return float(x.split(" ")[0])
            except:
                return np.nan
            
    def annotation(x):
            '''This function extracts Eurostat annotation "b, u, .."'''
            try:
                return x.split(" ")[1]
            except:
                return np.nan

    def columns_type(x):
            try:
                return int(x.strip())
            except:
                if x == "geo\\time":
                    return "var_" + "geo"
                else:
                    return "var_" + x

    
    # open the Eurostat TSV file 

    data = pd.read_csv(file_tsv, sep="\t")
    # Create a dataframe for values data
    data_clean = data
    # Clean data values with clean_cells function
    data_clean = data_clean.applymap(lambda x: x)
    # Drop column with variable name like "age,isced11,unit,sex,geo\time". It is the first column. we have a 
    # dataframe with only data values 
    data_clean.drop(data_clean.columns[0], axis = 1, inplace = True)
    # transform column with variable in multiple-columns  
    variabili = data[data.columns[0]].apply(lambda x: pd.Series(x.split(",")))
    variabili.columns = data.columns[0].split(",")
    # return cleaned dataframe in pandas dataframe
    result = pd.concat([variabili, data_clean], axis = 1)
    colonne  = list(map(lambda x: columns_type(x), list(result.columns.values)))
    result.columns = colonne
    colonne_var = result.columns.map(lambda x: str(x)[0:3] == "var")
    index = list(compress(result.columns, colonne_var))
    result = result.melt(id_vars = index)
    result["value_raw"] = result["value"]
    result["eurostat_annotation"] = result["value_raw"].apply(lambda x: annotation(x))
    result["value"] = result["value"].apply(clean_cells) 
    
    
    return result

In [4]:
#example 
#if __name__ == "__main__":
import urllib.request
import gzip

eurostat_link = "http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fcrim_off_cat.tsv.gz"
urllib.request.urlretrieve(eurostat_link , "crim_off_cat.tsv.gz")

('crim_off_cat.tsv.gz', <http.client.HTTPMessage at 0x7f0f9b233240>)

In [5]:
df = tsv_to_dataframe_long('crim_off_cat.tsv.gz')
df

var_iccs var_unit var_geo variable    value value_raw  \
0     ICCS0101       NR      AL     2015    54.00       54    
1     ICCS0101       NR      AT     2015    42.00       42    
2     ICCS0101       NR      BA     2015    56.00       56    
3     ICCS0101       NR      BE     2015   220.00      220    
4     ICCS0101       NR      BG     2015   129.00      129    
5     ICCS0101       NR      CH     2015    57.00       57    
6     ICCS0101       NR      CY     2015    12.00       12    
7     ICCS0101       NR      CZ     2015    84.00       84    
8     ICCS0101       NR      DE     2015   655.00      655    
9     ICCS0101       NR      DK     2015    46.00       46    
10    ICCS0101       NR      EE     2015    42.00       42    
11    ICCS0101       NR      EL     2015    86.00       86    
12    ICCS0101       NR      ES     2015   303.00      303    
13    ICCS0101       NR      FI     2015    88.00       88    
14    ICCS0101       NR      FR     2015  1017.00     1017    
15    ICCS0101       NR      HR     2015    37.00       37    
16    ICCS0101       NR      HU     2015    99.00       99    
17    ICCS0101       NR      IE     2015    61.00       61    
18    ICCS0101       NR      IS     2015     3.00        3    
19    ICCS0101       NR      IT     2015   469.00      469    
20    ICCS0101       NR      LI     2015     0.00        0    
21    ICCS0101       NR      LT     2015   168.00      168    
22    ICCS0101       NR      LU     2015     5.00        5    
23    ICCS0101       NR      LV     2015    81.00       81    
24    ICCS0101       NR      ME     2015    17.00       17    
25    ICCS0101       NR      MK     2015      NaN        :    
26    ICCS0101       NR      MT     2015     4.00        4    
27    ICCS0101       NR      NL     2015      NaN        :    
28    ICCS0101       NR      NO     2015      NaN        :    
29    ICCS0101       NR      PL     2015   286.00      286    
...        ...      ...     ...      ...      ...       ...   
8130  ICCS0601  P_HTHAB      EE     2008   116.40   116.40    
8131  ICCS0601  P_HTHAB      EL     2008   109.97   109.97    
8132  ICCS0601  P_HTHAB      ES     2008    31.89    31.89    
8133  ICCS0601  P_HTHAB      FI     2008   106.76   106.76    
8134  ICCS0601  P_HTHAB      FR     2008     9.57     9.57    
8135  ICCS0601  P_HTHAB      HR     2008   182.79   182.79    
8136  ICCS0601  P_HTHAB      HU     2008    54.39    54.39    
8137  ICCS0601  P_HTHAB      IE     2008   119.14   119.14    
8138  ICCS0601  P_HTHAB      IS     2008   463.13   463.13    
8139  ICCS0601  P_HTHAB      IT     2008    58.11    58.11    
8140  ICCS0601  P_HTHAB      LI     2008   593.96   593.96    
8141  ICCS0601  P_HTHAB      LT     2008    24.68    24.68    
8142  ICCS0601  P_HTHAB      LU     2008   277.59   277.59    
8143  ICCS0601  P_HTHAB      LV     2008   114.61   114.61    
8144  ICCS0601  P_HTHAB      ME     2008    74.73    74.73    
8145  ICCS0601  P_HTHAB      MK     2008    20.29    20.29    
8146  ICCS0601  P_HTHAB      MT     2008    44.14    44.14    
8147  ICCS0601  P_HTHAB      NL     2008   115.05   115.05    
8148  ICCS0601  P_HTHAB      NO     2008   370.41   370.41    
8149  ICCS0601  P_HTHAB      PL     2008     8.70     8.70    
8150  ICCS0601  P_HTHAB      PT     2008    35.33    35.33    
8151  ICCS0601  P_HTHAB      RO     2008    17.55    17.55    
8152  ICCS0601  P_HTHAB      RS     2008    82.13    82.13    
8153  ICCS0601  P_HTHAB      SE     2008    87.09    87.09    
8154  ICCS0601  P_HTHAB      SI     2008    71.33    71.33    
8155  ICCS0601  P_HTHAB      SK     2008    10.01    10.01    
8156  ICCS0601  P_HTHAB   UKC-L     2008    54.72    54.72    
8157  ICCS0601  P_HTHAB     UKM     2008   198.90   198.90    
8158  ICCS0601  P_HTHAB     UKN     2008    34.29    34.29    
8159  ICCS0601  P_HTHAB      XK     2008    14.58    14.58    

     eurostat_annotation  
0                         
1                         
2                 

In [6]:
for colonne in df.columns:
    print(df[colonne].unique())
    

['ICCS0101' 'ICCS0102' 'ICCS02011' 'ICCS020221' 'ICCS0301' 'ICCS03011'
 'ICCS03012' 'ICCS0401' 'ICCS0501' 'ICCS05012' 'ICCS0502' 'ICCS050211'
 'ICCS0601']
['NR' 'P_HTHAB']
['AL' 'AT' 'BA' 'BE' 'BG' 'CH' 'CY' 'CZ' 'DE' 'DK' 'EE' 'EL' 'ES' 'FI'
 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LI' 'LT' 'LU' 'LV' 'ME' 'MK' 'MT' 'NL'
 'NO' 'PL' 'PT' 'RO' 'RS' 'SE' 'SI' 'SK' 'TR' 'UKC-L' 'UKM' 'UKN' 'XK']
[2015 2014 2013 2012 2011 2010 2009 2008]
[ 54.    42.    56.   ... 198.9   34.29  14.58]
['54 ' '42 ' '56 ' ... '198.90 ' '34.29 ' '14.58 ']
['']


In [7]:
df["var_iccs"][0]=="ICCS0101"

True

In [17]:
cond1=df["var_iccs"]=="ICCS0101"
cond2=df["var_iccs"]=="ICCS02011"
cond3=df["var_iccs"]=="ICCS0301"
cond4=df["var_iccs"]=="ICCS03011"

In [18]:
reatigravi = df[cond1 | cond2 | cond3 | cond4]
reatigravi

var_iccs var_unit var_geo variable    value value_raw  \
0      ICCS0101       NR      AL     2015    54.00       54    
1      ICCS0101       NR      AT     2015    42.00       42    
2      ICCS0101       NR      BA     2015    56.00       56    
3      ICCS0101       NR      BE     2015   220.00      220    
4      ICCS0101       NR      BG     2015   129.00      129    
5      ICCS0101       NR      CH     2015    57.00       57    
6      ICCS0101       NR      CY     2015    12.00       12    
7      ICCS0101       NR      CZ     2015    84.00       84    
8      ICCS0101       NR      DE     2015   655.00      655    
9      ICCS0101       NR      DK     2015    46.00       46    
10     ICCS0101       NR      EE     2015    42.00       42    
11     ICCS0101       NR      EL     2015    86.00       86    
12     ICCS0101       NR      ES     2015   303.00      303    
13     ICCS0101       NR      FI     2015    88.00       88    
14     ICCS0101       NR      FR     2015  1017.00     1017    
15     ICCS0101       NR      HR     2015    37.00       37    
16     ICCS0101       NR      HU     2015    99.00       99    
17     ICCS0101       NR      IE     2015    61.00       61    
18     ICCS0101       NR      IS     2015     3.00        3    
19     ICCS0101       NR      IT     2015   469.00      469    
20     ICCS0101       NR      LI     2015     0.00        0    
21     ICCS0101       NR      LT     2015   168.00      168    
22     ICCS0101       NR      LU     2015     5.00        5    
23     ICCS0101       NR      LV     2015    81.00       81    
24     ICCS0101       NR      ME     2015    17.00       17    
25     ICCS0101       NR      MK     2015      NaN        :    
26     ICCS0101       NR      MT     2015     4.00        4    
27     ICCS0101       NR      NL     2015      NaN        :    
28     ICCS0101       NR      NO     2015      NaN        :    
29     ICCS0101       NR      PL     2015   286.00      286    
...         ...      ...     ...      ...      ...       ...   
7573  ICCS03011  P_HTHAB      DK     2008    17.81    17.81    
7574  ICCS03011  P_HTHAB      EE     2008    11.95    11.95    
7575  ICCS03011  P_HTHAB      EL     2008     2.07     2.07    
7576  ICCS03011  P_HTHAB      ES     2008     5.34     5.34    
7577  ICCS03011  P_HTHAB      FI     2008    17.26    17.26    
7578  ICCS03011  P_HTHAB      FR     2008    16.06    16.06    
7579  ICCS03011  P_HTHAB      HR     2008     4.36     4.36    
7580  ICCS03011  P_HTHAB      HU     2008     2.13     2.13    
7581  ICCS03011  P_HTHAB      IE     2008     7.81     7.81    
7582  ICCS03011  P_HTHAB      IS     2008    21.56    21.56    
7583  ICCS03011  P_HTHAB      LI     2008     8.49     8.49    
7584  ICCS03011  P_HTHAB      LT     2008     5.10     5.10    
7585  ICCS03011  P_HTHAB      LU     2008    11.78    11.78    
7586  ICCS03011  P_HTHAB      LV     2008     4.56     4.56    
7587  ICCS03011  P_HTHAB      ME     2008     2.76     2.76    
7588  ICCS03011  P_HTHAB      MK     2008     2.00     2.00    
7589  ICCS03011  P_HTHAB      MT     2008     4.66     4.66    
7590  ICCS03011  P_HTHAB      NL     2008    11.86    11.86    
7591  ICCS03011  P_HTHAB      NO     2008    19.93    19.93    
7592  ICCS03011  P_HTHAB      PL     2008     4.23     4.23    
7593  ICCS03011  P_HTHAB      PT     2008     2.98     2.98    
7594  ICCS03011  P_HTHAB      RO     2008     4.92     4.92    
7595  ICCS03011  P_HTHAB      RS     2008     1.67     1.67    
7596  ICCS03011  P_HTHAB      SE     2008    53.37    53.37    
7597  ICCS03011  P_HTHAB      SI     2008     2.84     2.84    
7598  ICCS03011  P_HTHAB      SK     2008     2.83     2.83    
7599  ICCS03011  P_HTHAB   UKC-L     2008    23.98    23.98    
7600  ICCS03011  P_HTHAB     UKM     2008    15.83    15.83    
7601  ICCS03011  P_HTHAB     UKN     2008    20.79    20.79    
7602  ICCS03011  P_HTHAB      XK     2008     2.32     2.32    

     eurostat_annotation  
0          

In [19]:
for colonne in reatigravi.columns:
    print(reatigravi[colonne].unique())

['ICCS0101' 'ICCS02011' 'ICCS0301' 'ICCS03011']
['NR' 'P_HTHAB']
['AL' 'AT' 'BA' 'BE' 'BG' 'CH' 'CY' 'CZ' 'DE' 'DK' 'EE' 'EL' 'ES' 'FI'
 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LI' 'LT' 'LU' 'LV' 'ME' 'MK' 'MT' 'NL'
 'NO' 'PL' 'PT' 'RO' 'RS' 'SE' 'SI' 'SK' 'TR' 'UKC-L' 'UKM' 'UKN' 'XK']
[2015 2014 2013 2012 2011 2010 2009 2008]
[54.   42.   56.   ... 23.98 15.83  2.32]
['54 ' '42 ' '56 ' ... '23.98 ' '15.83 ' '2.32 ']
['']


In [24]:
pd.pivot_table(reatigravi, values = "value",
               index = "var_iccs",
               aggfunc = np.mean)

value
var_iccs               
ICCS0101      90.142436
ICCS02011  16311.787460
ICCS0301    2860.134355
ICCS03011    829.912360

In [21]:
pd.pivot_table(reatigravi, values = "value",
               index = ["var_geo","var_iccs"],
               aggfunc = [np.mean,np.std]).T

var_geo            AL                                           AT  \
var_iccs     ICCS0101   ICCS02011   ICCS0301  ICCS03011   ICCS0101   
mean value  73.248182  158.029091  55.575455  25.643636  30.483750   
std  value  49.373333  125.756997  45.308520  18.495160  32.837244   

var_geo                                                  BA              \
var_iccs      ICCS02011     ICCS0301   ICCS03011   ICCS0101   ICCS02011   
mean value  1918.545000  1918.608750  559.820000  34.976154  499.505455   
std  value  1940.317161  1943.260498  587.534098  28.171624  464.737978   

var_geo       ...              UKM                    UKN              \
var_iccs      ...         ICCS0301   ICCS03011   ICCS0101   ICCS02011   
mean value    ...      3218.625714  636.390714  11.871875  712.319375   
std  value    ...      3372.289334  687.861574  11.229724  671.058154   

var_geo                                     XK                           \
var_iccs       ICCS0301   ICCS03011   ICCS0101    ICCS02011    ICCS0301   
mean value  1097.619375  277.416250  47.571667  1781.248333  104.938333   
std  value  1053.706034  268.109514  40.784394  1669.112236   76.649678   

var_geo                
var_iccs    ICCS03011  
mean value  24.097500  
std  value  17.759004  

[2 rows x 159 columns]

In [29]:
cond = reatigravi["var_geo"].isin(["IT","ES","DE","FR"])
eurogravi=reatigravi[cond]

In [30]:
pd.pivot_table(eurogravi, values = "value",
               index = ["var_geo","var_iccs"],
               aggfunc = [np.mean,np.std]).T

var_geo             DE                                                    ES  \
var_iccs      ICCS0101      ICCS02011      ICCS0301    ICCS03011    ICCS0101   
mean value  332.096250   91793.036250  20000.779375  3734.285625  181.451875   
std  value  343.048845  132412.302564  21373.379290  3852.963731  189.290852   

var_geo                                                    FR                 \
var_iccs       ICCS02011     ICCS0301   ICCS03011    ICCS0101      ICCS02011   
mean value  17347.808750  4868.276875  790.764375  429.533125  113822.586875   
std  value  25430.618166  5024.107448  867.515831  447.774255  117788.422168   

var_geo                                        IT                
var_iccs        ICCS0301    ICCS03011    ICCS0101     ICCS02011  
mean value  13306.549375  5496.039375  266.946875  33232.671250  
std  value  13939.908836  5707.085324  277.032888  34230.096778

In [36]:
eurogravi.groupby("var_geo").mean()

value
var_geo              
DE       28965.049375
ES        5797.075469
FR       33263.677188
IT       16749.809063

In [46]:
eurogravi.columns

Index(['reati', 'var_unit', 'var_geo', 'variable', 'value', 'value_raw',
       'eurostat_annotation'],
      dtype='object')

In [47]:
eurogravi.columns = ['reati', 'var_unit', 'nazione', 'anno', 'valore', 'value_raw',
       'eurostat_annotation']

In [53]:
def cambionome(reato):
    if reato == "ICCS0101":
        return "omicidio intenzionale"
    if reato == "ICCS02011":
        return "aggressione"
    if reato == "ICCS0301":
        return "violenza sessuale"
    if reato == "ICCS03011":
        return "stupro"

In [55]:
eurogravi["reati"]=eurogravi["reati"].apply(cambionome)

/anaconda/envs/py35/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [61]:
eurogravi=eurogravi.reset_index(drop=True)